[package]
name = "vault"
edition = "2024"

[addresses]
vault = "0x0"

[dev-dependencies]

[dev-addresses]

[dependencies.Pyth]
git = "https://github.com/pyth-network/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-contract-mainnet"

[dependencies.clmm_pool]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "clmm_pool"
rev = "main"
override = true

[dependencies.integer_mate]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "integer_mate"
rev = "main"
override = true

[dependencies.move_stl]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "move_stl"
rev = "main"
override = true

[dependencies.gauge_cap]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "gauge_cap"
rev = "main"
override = true

[dependencies.price_provider]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "price_provider"
rev = "main"
override = true

[dependencies.locker_cap]
local = "../locker_cap"

[dependencies.voting_escrow]
local = "../voting_escrow"

[dependencies.Switchboard]
git = "https://github.com/LFBuild/sui.git"
subdir = "on_demand/"
rev = "mainnet"

[dependencies.price_monitor]
local = "../price_monitor"

[dependencies.governance]
local = "../governance"